### ISSUE TITLE
Тестування інтерфейсу

### ISSUE THREAD

**Issue by Maksim23777** [Maksim23777/GoodFood#5]
Ваше завдання - провести тестування інтерфейсу нашого продукту з метою визначення його простоти та зрозумілості для користувачів. Будь ласка, зосередьтеся на наступних аспектах:

**Comment by Goods79** [comment]
Тестування інтерфейсу проведено — 
1. Інтерфейс інтуїтивно зрозумілий
2. Навігація зручна, користувач легко знаходить необхідну інформацію та функції (Наочний перехід до меню із стравами, кнопка Зробити замовлення має правильний розмір і колір, тому її легко помітити)
3. Взаємодія з інтерфейсом - користувач безперебійно має можливість вводити дані через поля (реєстрація/авторизація)
  Програма без помилок виводить необхідну інформацію користувачу (інформація про застосунок, меню страв разом із відповідними фото, зворотній звʼязок)

**Comment by Goods79** [comment]
Я проводив тестування і успішно перевірив функціонал який розробив наш розробник для нашого продукту. Ось список функцій, які були перевірені:

Оформлення замовлення.
Додавання та видалення страв.
Відгуки 
Покращений інтерфейс меню.
Під час тестування я виявив помилку: після додавання страви в кошик в пункті "ціна" відображається не ціна, а вага.

Моя рекомендація щодо виправлення цієї помилки полягає в наступному:
Переконайтеся, що відображається правильна інформація про ціну страви в кошику після її додавання. Ціна повинна бути вказана коректно, і якщо є варіанти вибору (наприклад, розмір порції), то користувач повинен бачити відповідні ціни для кожного варіанту.

Якщо потрібно, зверніть увагу на код, який відповідає за відображення ціни в кошику, та переконайтеся, що він працює правильно і відображає потрібну інформацію.
