### ISSUE TITLE
Виправлення несправності 

### ISSUE THREAD

**Issue by Maksim23777** [Maksim23777/GoodFood#8]
Тестувальник виявив помилку при тестуванні функціоналу , що після додавання страви в кошик в пункті ціна  відображається не ціна а вага                                                                                                         
       Його рекомендація щодо виправлення цієї помилки полягає в наступному:
Переконайтеся, що відображається правильна інформація про ціну страви в кошику після її додавання. Ціна повинна бути вказана коректно, і якщо є варіанти вибору (наприклад, розмір порції), то користувач повинен бачити відповідні ціни для кожного варіанту.

**Comment by Vlad2526** [comment]
Зрозумів, виправлю
