### ISSUE TITLE
Проведи загальне тестування нашої програми 

### ISSUE THREAD

**Issue by Maksim23777** [Maksim23777/GoodFood#9]
[АСУ ОЗК.txt](https://github.com/Maksim23777/GoodFood/files/12142014/default.txt)

**Comment by Goods79** [comment]
1. Тестування інтерфейсу:
Інтерфейс зручний та інтуїтивно зрозумілий. Користувач легко зрозуміє як зробити замовлення, доступ до інших функцій також цілком зрозумілий, як приклад, взаємодія із кошиком.
2. Функціональне тестування:
Реєстрація/авторизація проходить безпомилково
Замовлення створюються, відстежуються та скасовуються успішно.
Авторизація під різними правами доступу до програми успішна (Звичайний користувач отримує всі заплановані можливості, адміністратор та офіціант отримують окремий функціонал)
3. Тестування бази даних:
  Дані користувачів при реєстрації зберігаються успішно
  Інформація про замовлення клієнтів зберігаються у БД успішно
  Меню зі стравами працює, успішно виводить страви у програму, та успішно додаються страви, які може редагувати адмін
4. Тестування безпеки:  
   При збереженні даних користувачів при реєстрації, паролі у БД гешуються методом SAH256
